services:
  - type: web
    name: youtube-transcript
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: your_api_key_here
    plan: free
`